### ISSUE TITLE
Multiple fill values in the same SVG?

### ISSUE THREAD

**Issue by NeverwinterMoon** [kisenka/svg-fill-loader#15]
Is it somehow possible to colour different elements with different colours in the same SVG? I see that selector can just narrow down which fills are selected, but the value of the colour can still be provided only once. Is this correct? If this is so, is it planned to have this feature in the future? We would certainly love it in our project.

**Comment by kisenka** [comment]
This loader is moved to svg-mixer project and renamed to [svg-transform-loader](https://github.com/kisenka/svg-mixer/tree/master/packages/svg-transform-loader).
In svg-transform-loader it's possible with following manner:

```css
.img {
  background-image: url('./img.svg?fill=red .selector1, blue .selector2')
}
```
