### ISSUE TITLE
Support more attributes such as stroke

### ISSUE THREAD

**Issue by SchneiderOr** [kisenka/svg-fill-loader#16]
Hey fellows,
you did a great job with this loader, although my use case requires combination of fill and stroke together,

is there's any chance you'll add support for more attributes?

Thanks,
Or

**Comment by kisenka** [comment]
Yeah, but it weird to pass multiple params as query params. You import SVGs from CSS?

**Comment by SchneiderOr** [comment]
Yes, im using css, my use case is few assets that has both fill and stroke that need to be manipulated.

**Comment by gqbre** [comment]
I need that~~ that is useful

**Comment by kisenka** [comment]
@SchneiderOr @gqbre ok, what you say about PostCSS plugin which move some CSS declarations to url? E.g:

```css
.image {
  background-image: url('image.svg');
  fill: #ff00ee;
  stroke: #000;
}
```

Will be translated to:
```css
.image {
  background-image: url('image.svg?fill=%23ff00ee&stroke=%23000');
}
```

This allows to pass any complex parameters to loader and keep code clean. Also there is no need for encodeSharpLoader, which is ugly hack for working with css-loader.
What do you think?

**Comment by gqbre** [comment]
I set fill and stroke to 'currentColor' in svg files.
So I can use 'color' in CSS to control it~
I did it by myself, thanks.

**Comment by kisenka** [comment]
@gqbre is it works for SVGs imported from CSS as background image?

**Comment by gqbre** [comment]
@kisenka , no, I use svg-sprite

**Comment by kisenka** [comment]
@gqbre I mean how you import SVGs? 

Like this
```js
import image from './img/image.svg';
```

or
```css
.image {
  background-image: url('./image.svg');
}
```

?

**Comment by gqbre** [comment]
@kisenka 
` import image from './img/image.svg';`
this way

**Comment by kisenka** [comment]
@gqbre ok, this isn't your case. I am asking @SchneiderOr

**Comment by SchneiderOr** [comment]
@kisenka its a really food idea to move it to be a postcss-loader, it abstract away the encode sharp issue and let you treat it more declarative and nice in your css.

I can help with it, do you have gitter or a tasks list for this issue?

**Comment by SchneiderOr** [comment]
I solved my issue using postcss-iinesvg which has full support for every property you wish to maniulate though the api is not that convinencr as you suggested to the postcss plugin (more like background-image: svg-load('someUrl/icon.svg', fill=red, stroke=green).

If you wish to make a more declarative css like plugin let me know and we will could make it happen.

Or

**Comment by SchneiderOr** [comment]
* postcss-inline-svg

**Comment by Abdelhady** [comment]
I think it would be better for svg-fill-loader to support passing an important parameter like `stroke`,
actually, I had to switch to postcss-inline-svg to be able to pass the `stroke`.

**Comment by franciscolourenco** [comment]
+1 for stroke, please reopen

**Comment by kisenka** [comment]
This loader is moved to svg-mixer project and renamed to [svg-transform-loader](https://github.com/kisenka/svg-mixer/tree/master/packages/svg-transform-loader).
In svg-transform-loader any attribute is allowed, eg:

```css
.img {
  background-image: url('./img.svg?fill=red&fill-rule=nonzero&fill-opacity=0.5')
}
```
